### ISSUE TITLE
README 中的示意图是用什么软件画的？

### ISSUE THREAD

**Issue by Bpazy** [bingoohuang/tannangquwu#1]
README 中的示意图是用什么软件画的？

就是下图：
![](https://user-images.githubusercontent.com/1940588/92542108-7ae54880-f27a-11ea-8fd2-21aadf9984c9.png)

**Comment by bingoohuang** [comment]
vscode+drawio插件，原图文件在此：https://github.com/bingoohuang/tannangquwu/blob/master/_scripts/rationale.drawio
